"""Revision ID: 1d93332f60c5
Revises: cd5c1f39424c
Create Date: 2025-10-24 02:01:33.693948+00:00
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d93332f60c5'
down_revision = 'cd5c1f39424c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
